### ISSUE TITLE
Error message "insufficient account balance when creating "ask" order

### ISSUE THREAD

**Issue by rene78** [lightninglabs/pool#186] opened 2020-12-05 15:33 UTC
Trying to create an "ask" order over 100.000sat but get the error message "insufficient account balance" even though I funded my account with this sum. Is it related to transaction fees?

`pool orders submit ask 100000 024878514bce38d14031f71f5a4c6d1f9d1ac427ad813c55dd5f30970b3edeb3b2 --interest_rate_percent=1 --lease_duration_blocks=2016`

![image](https://user-images.githubusercontent.com/36115705/101247006-01dd7c00-3717-11eb-944b-870d4f7e0d9c.png)

**Comment by guggero** [comment] 2020-12-07 08:28
With your account you also have to be able to pay for the order execution fees and your ask's part of the chain fees. Therefore the account size must be greater than `ask_size + execution_fee + chain_fees`. How high the chain fees are depends on your setting of `--max_batch_fee_rate` which will influence under what fee conditions the ask is executed (if you set it too low it can take a long time for your order to be matched of the mempool never gets that empty).

All of this is described in more detail here: https://github.com/lightninglabs/pool/blob/master/docs/orders.md#order-execution-fees

Closing as this is not a bug.

**Closed by guggero** 2020-12-07 08:28 UTC
