### ISSUE TITLE
Problem closing lightning pool account

### ISSUE THREAD

**Issue by RothbardMmurray** [lightninglabs/pool#466] opened 2023-09-08 18:54 UTC
I'm having an issue with closing an account on the lighting pool. I send back the fund with too low fees hoping to open a channel with higger fees later to bump the closing transaction. However, there was some issue with the channel transaction. It never appeared in the mempool but appears in my node as pending. Thus, I can't move the funds and am waiting for confirmation of that transaction. Is it possible to bump that transaction fee? I will pay you the fees if it does. 
 
 

Pool closing transaction:
 
df338aaaf768499d521f869c608261c5c432364b55097ca3dfee5e94efcaa694

**Comment by positiveblue** [comment] 2023-09-08 19:01
It looks like the tx fee is too low to fit in the "standard" mempool size (300Mb)

The current purging threshold for the 300Mb [mempool is ~8 sat/vbyte](https://mempool.space/) while the [tx was broadcasted at 5 sat/vbyte](https://mempool.space/tx/df338aaaf768499d521f869c608261c5c432364b55097ca3dfee5e94efcaa694).

To bump the tx with a CPFP the tx must be in the mempool. You can try increasing the size of your mempool and then you will be able to broadcast and bump the tx.

In order to have it propagated to the miners, other nodes MUST also have the closing tx (5 sat/vbyte) in their mempool. So even if your node tries to broadcast it to the network you may have to wait a bit until the initial tx fee is higher than the mempool purge threshold.

**Comment by RothbardMmurray** [comment] 2023-09-08 19:05
I did that. change the side to 500mb. bumped the fee and only appear in my mempool.  

Bumped transaction
420342ee4a9ceaa9f05939c00eb928807061fdbbaa9339d399ee42fd3429f07c

**Comment by guggero** [comment] 2023-09-11 07:55
Looks like the TX got confirmed.

**Closed by guggero** 2023-09-11 07:55 UTC
