### ISSUE TITLE
[WRN] ORDR: Unable to abandon channel ? Is thad bad?

### ISSUE THREAD

**Issue by rsnel** [lightninglabs/pool#136] opened 2020-11-05 05:17 UTC
I'm not sure if this is the right place to ask...

I have a couple of asks in the system. Sometimes poold says: "preparing channel funding for 1 orders" and nothing happens (for >12 hours). All orders stay in state ORDER_SUBMITTED. The warning message I see is: "[WRN] ORDR: Unable to abandon channel (channel_point=blabla) ". Does something prevent my orders getting executed, is pooled talking about someone else's orders?

lncli listchannels | grep -e channel_point does not show anything

**Comment by Roasbeef** [comment] 2020-11-05 05:29
The warning log is benign, it just tries to clear any lingering channel shims (an `lnd` API that `poold` uses to fund the channels) each time it processes a batch. 

If you're seeing these logs frequently, then: can your node be connected to by external nodes on the public internet? Alternatively, do you have any filtered logs of failed connection attempts as well?

**Comment by rsnel** [comment] 2020-11-05 08:32
Thanks for your quick response. It turned out that my node was not reachable due to a configuration error on my side.... Now the node should be reachable. I will report back if this fixes the issue.

**Comment by rsnel** [comment] 2020-11-06 15:03
It turned out that my node still was unreachable (i got one match durgin that time, the warning did not appear, but nothing happened). Now it is really reachable, but I don't get "preparing channel.." anymore. Could it be that my node is blacklisted because it was unreachable?

**Comment by guggero** [comment] 2020-11-06 15:20
Yes, the auction server keeps a list of nodes that have problems and suspends them from being matched to avoid trying over and over again. I manually cleared the suspend list now and your orders should be considered again in the next batch.

**Comment by guggero** [comment] 2020-11-06 15:22
Closing the issue as the problem seems to be fixed by making the node reachable.
Feel free to re-open if you run into problems again.

**Closed by guggero** 2020-11-06 15:22 UTC

**Comment by rsnel** [comment] 2020-11-06 19:42
I still have the problem. Node is confirmed to be reachable over ipv4 and ipv6. My debug logs were already rotated away when I went to look for error messages related to my problem. I'm currently running poold and lnd with level debug. Can you please clear the suspend list once again?

**Comment by guggero** [comment] 2020-11-07 10:04
When you run `lncli pendingchannels` do you see any of the channels that are mentioned in the error message?

I think we might just need to demote that message to INF as it can happen during the normal matchmaking flow and normally doesn't have any consequences.
To answer your question "is that bad": Most likely not. You can check your `lncli pendingchannels` and look up the transaction ID (the first part of `channel_point` before the colon) on a block explorer. If you have lots of channels where you don't find the TX on an explorer, we might need to investigate (and I'll re-open the issue).
If you don't have any pending channels or they all have a funding transaction that made it to the mempool or confirmed, you can just ignore those error messages.

For anyone finding this issue, here's what the error usually means:
1. Your order is matched with a node that isn't properly reachable (this itself will hopefully be fixed soon by doing a connectivity check before submitting orders).
1. Your `lnd` tries to connect to the node of your matched order.
1. The connection fails (the channel was never opened and never added to your node's channel database) and your `poold` rejects the batch.
1. The auctioneer tries to match you with someone else, sends a new batch.
1. Your `poold` tries to clean up all (abandon) channels from the previous attempt as they will certainly never be valid (the new batch also has a new TXID).
1. The channel that never opened cannot be found and therefore not be abandoned which leads to the error message.
1. Your node opens the channels of the new batch, everything completes normally.

So you see, in this scenario, the error message is actually expected and can be ignored.
