### ISSUE TITLE
Feature Request: Expose 'sidecar printticket' command to the grpc api

### ISSUE THREAD

**Issue by sako0938** [lightninglabs/pool#276] opened 2021-07-30 04:16 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to get sidecar channels working, and it is often useful to decode the sidecar ticket to see the state of things, and as a sanity check. Current this isnt exposed on the grpc interface so I have to have another shell open to run `pool sidecar printticket {ticket}`.

**Describe the solution you'd like**
A rpc command named PrintTicket should be added, which can handle this should be made available.

**Comment by guggero** [comment] 2021-07-30 08:02
Duplicate of https://github.com/lightninglabs/pool/issues/263.

**Closed by guggero** 2021-07-30 08:02 UTC
